name: 'GitHub Action for Vultr - vultr-cli'
description: 'Use vultr-cli to manage your Vultr resources.'
author: 'techknowlogick <techknowlogick@gitea.io>'
inputs:
  version:
    description: 'Version of vultr-cli to install'
    default: 'latest'
  token:
    description: 'Vultr API Key'
    required: true
  command:
    description: 'Command to run to verify API key'
    default: 'account'
runs:
  using: 'node12'
  main: 'dist/index.js'
